### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [erskin19/RailsModels#1]
I like that you attempted a custom validation, but it looks like [this line](https://github.com/erskin19/RailsModels/blob/master/app/models/commenter.rb#L4) should _always_ result in an error. You're trying to access a `start` attribute on your model, when the model doesn't _have_ a `start` attribute. I'm guessing you meant this for your `created` attribute?

This kind of validation should also never be necessary, since you've already specified in the database that you will only accept valid datetimes. That means any non-valid datetimes, if they managed to sneak in, would simply be translated to `nil`. So you could validate that `created` is always a valid datetime by simply validating that it's present.

Since Rails already keeps track of when a record was created though (in a `created_at` attribute), let's just remove the `created` column in the database (you can [see how here](http://stackoverflow.com/questions/2831059/how-to-drop-columns-using-rails-migration#answer-3742902)). Then you can remove traces of `created` from your views and controller.

**Comment by erskin19** [comment]
Should be fixed

**Comment by chrisvfritz** [comment]
:+1: Looks good.
